version: "3"

services:
  app:
    build: ./app
    env_file: .env
    restart: on-failure
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./app:/usr/src/app
    command: python manage.py runserver 0.0.0.0:${APP_PORT}
    links:
      - db
      - redis
      - rabbitmq
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    command: redis-server
    volumes:
      - ./data/redis:/var/lib/ redis/data
    ports:
      - ${REDIS_PORT}:6379
  celery_worker:
    build: ./app
    env_file: .env
    command: celery worker --app=core --loglevel=INFO
    restart: on-failure
    volumes:
      - ./app:/usr/src/app
    links:
      - db
      - redis
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.8.14-alpine
    restart: on-failure
    ports:
      - ${RMQ_PORT}:5672
